// Generated by CoffeeScript 1.6.2
var SIMLBrunch, siml;

siml = require('siml');

module.exports = SIMLBrunch = (function() {
  function SIMLBrunch() {}

  SIMLBrunch.prototype.brunchPlugin = true;

  SIMLBrunch.prototype.type = 'template';

  SIMLBrunch.prototype.extension = 'siml';

  SIMLBrunch.prototype.compile = function(data, path, callback) {
    var content, error, ex;

    try {
      content = siml.angular.parse(data, {
        pretty: false
      });
      content = content.replace(/'/g, "\\'");
      return content = "module.exports = function() { return '" + content + "' }";
    } catch (_error) {
      ex = _error;
      error = "Error: " + ex.message;
      if (ex.type) {
        error = ex.type + error;
      }
      if (ex.filename) {
        return error += " in '" + ex.filename + ":" + ex.line + ":" + ex.column + "'";
      }
    } finally {
      callback(error, content);
    }
  };

  return SIMLBrunch;

})();
